version: '3.8'

services:
  ros2_dev:
    build:
      context: .
      # args:
      #   # Docker Compose will now read the values for these variables
      #   # from the .env file or use the defaults provided.
      #   - UID=${UID:-1000}
      #   - GID=${GID:-1000}
      #   - VIDEO_GID=${VIDEO_GID}
    image: ros2-dev-sudo-user
    container_name: ros2_head_container
    environment:
      - ROS_DISTRO=jazzy
      - DISPLAY=${DISPLAY}
      - XDG_RUNTIME_DIR=/tmp/runtime-docker
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/home/docker_user/.Xauthority:rw
      - /usr/lib/aarch64-linux-gnu:/usr/lib/aarch64-linux-gnu:ro
      - /lib/firmware:/lib/firmware
      - /lib/udev/rules.d:/lib/udev/rules.d 
      - /lib/modules:/lib/modules

    devices:
      - /dev/video0:/dev/video6
      - /dev/ttyACM0:/dev/ttyACM0
      - /dev/dri:/dev/dri            # For GPU hardware acceleration
      - /dev/hailo0:/dev/hailo0    # Hailo device
      
    network_mode: "host"
    privileged: true
    stdin_open: true
    tty: true