version: '3.8'

services:
  ros2_dev:
    build:
      context: .
      # args:
      #   # Docker Compose will now read the values for these variables
      #   # from the .env file or use the defaults provided.
      #   - UID=${UID:-1000}
      #   - GID=${GID:-1000}
      #   - VIDEO_GID=${VIDEO_GID}
    image: ros2-dev-sudo-user
    privileged: true
    container_name: ros2_head_container
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/home/docker_user/.Xauthority
      # --- FIX IS HERE (1/2) ---
      # Explicitly tell Mesa where to find the hardware drivers we are mounting.
      - LIBGL_DRIVERS_PATH=/usr/lib/aarch64-linux-gnu/dri
    volumes:
      - ./ros2_ws:/home/docker_user/ros2_ws
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/home/docker_user/.Xauthority:rw
      # --- FIX IS HERE (2/2) ---
      # Mount the host's GPU driver directory into the container (read-only).
      - /usr/lib/aarch64-linux-gnu/dri:/usr/lib/aarch64-linux-gnu/dri:ro
    devices:
      - /dev/video0:/dev/video0
      - /dev/ttyACM0:/dev/ttyACM0
      - /dev/dri:/dev/dri
      - /dev/fb0:/dev/fb0
    network_mode: "host"
    stdin_open: true