version: '3.8'

services:
  ros2_dev:
    build:
      context: .
      # args:
      #   # Docker Compose will now read the values for these variables
      #   # from the .env file or use the defaults provided.
      #   - UID=${UID:-1000}
      #   - GID=${GID:-1000}
      #   - VIDEO_GID=${VIDEO_GID}
    image: ros2-dev-sudo-user
    container_name: ros2_head_container
    environment:
      - ROS_DISTRO=humble
      - DISPLAY=${DISPLAY}
    volumes:
      - ./ros2_ws:/home/docker_user/ros2_ws
      - /tmp/.X11-unix:/tmp/.X11-unix
    devices:
      - /dev/video6:/dev/video6#
      - /dev/ttyACM0:/dev/ttyACM0
    network_mode: "host"
    stdin_open: true
    tty: true